spring:
  application:
    name: EBANKING
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BDCRG;trustServerCertificate=true;encrypt=true
    username: sa
    password: doukoure93
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none
  cloud:
    config:
      enabled: false

application:
  title: DIGICRG-MICROSERVICE
  version: v02

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      # Use discovery server service name
      defaultZone: http://admin:admin2711@discoveryserver:5002/eureka/

jwks:
  # Use authorization server service name
  uri: http://authorizationserver:8080/oauth2/jwks

# Reduced logging for Docker environment
logging:
  level:
    org:
      hibernate:
        SQL: INFO
      springframework:
        jdbc:
          core: INFO
    com.netflix.discovery: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 120000