spring:
  application:
    name: EBANKING

  # Configuration DataSource Production (existante)
  datasource:
    url: jdbc:sqlserver://10.110.15.2:1433;databaseName=BDCRG_TEST;trustServerCertificate=true;encrypt=true
    username: sa
    password: 1234567
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    initialize: true
    hikari:
      pool-name: ProductionPool
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 60000
      initialization-fail-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 600000

  # Configuration DataSource Middleware (nouvelle)
  middleware:
    datasource:
      url: jdbc:sqlserver://10.220.220.11:1433;databaseName=BD_MIDDLEWARE;trustServerCertificate=true;encrypt=true
      username: sa
      password: 1234
      # Add Hikari configuration for middleware too
      hikari:
        pool-name: MiddlewarePool
        maximum-pool-size: 5
        minimum-idle: 2
        connection-timeout: 60000
        initialization-fail-timeout: 60000
        idle-timeout: 300000
        max-lifetime: 600000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: none

  cloud:
    config:
      enabled: false

  profiles:
    active: default

# Configuration Application
application:
  title: DIGICRG-MICROSERVICE
  version: v02

# Configuration Serveur
server:
  port: 8081

# Configuration Eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin2711@localhost:5002/eureka/

# Configuration JWKS (IMPORTANT - Cette ligne manquait!)
jwks:
  uri: http://localhost:8080/oauth2/jwks

# Configuration Logging
logging:
  level:
    io.digiservices.ebanking: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core: DEBUG

# Configuration Feign
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 120000