package io.digiservices.notificationservice.enumeration;

public enum EventType {
    RESETPASSWORD, USER_CREATED, STOCK_VALIDATED,STOCK_REJECTED,NEW_MESSAGE, TICKET_CREATED, COMMENT_CREATED, FILE_UPLOADED, ACCOUNT_VERIFIED
}
