// src/app/interface/reference-data.interface.ts

export interface ReferenceOption {
    code: string;
    label: string;
    codEmpresa?: string;
}

export interface DistrictOption extends ReferenceOption {
    codPays: string;
    codProvincia: string;
    codCanton?: string;
    codDistrito: string;
}

export class ReferenceData {
    // Secteurs d'activité
    static readonly SECTORS: ReferenceOption[] = [
        { code: '101', label: 'PRIMAIRE', codEmpresa: '00000' },
        { code: '102', label: 'SECONDAIRE', codEmpresa: '00000' },
        { code: '103', label: 'TERTIAIRE', codEmpresa: '00000' },
        { code: '104', label: 'QUATERNAIRE', codEmpresa: '00000' }
    ];

    // Activités
    static readonly ACTIVITIES: ReferenceOption[] = [
        { code: '101', label: 'AGRICULTURE ELEVAGE ET PECHE', codEmpresa: '00000' },
        { code: '102', label: 'COMMERCE', codEmpresa: '00000' },
        { code: '103', label: 'HOTELERIE ET RESTAURATION', codEmpresa: '00000' },
        { code: '104', label: 'ARTISANAT', codEmpresa: '00000' },
        { code: '105', label: 'SERVICE ET FORMATION', codEmpresa: '00000' },
        { code: '106', label: 'TRANSPORT ET AUTRES', codEmpresa: '00000' },
        { code: '107', label: 'IMMOBILIER ET LOGEMENT', codEmpresa: '00000' },
        { code: '108', label: 'BATIMENTS ET TRAVAUX PUBLICS', codEmpresa: '00000' },
        { code: '109', label: 'MINES ET GEOLOGIE', codEmpresa: '00000' },
        { code: '110', label: 'FONCTIONNAIRES ET SALARIES', codEmpresa: '00000' }
    ];

    // Professions
    static readonly PROFESSIONS: ReferenceOption[] = [
        { code: '101', label: 'CULTIVATEUR', codEmpresa: '00000' },
        { code: '102', label: 'ARTISAN', codEmpresa: '00000' },
        { code: '103', label: 'MECANICIEN', codEmpresa: '00000' },
        { code: '104', label: 'CHAUFFEUR', codEmpresa: '00000' },
        { code: '105', label: 'COMMERCANT', codEmpresa: '00000' },
        { code: '106', label: 'ENTREPRENEUR', codEmpresa: '00000' },
        { code: '107', label: 'ETUDIANT', codEmpresa: '00000' },
        { code: '108', label: 'FONCTIONNAIRE', codEmpresa: '00000' },
        { code: '109', label: 'JOURNALIER', codEmpresa: '00000' },
        { code: '110', label: 'MENAGERE', codEmpresa: '00000' },
        { code: '111', label: 'PECHEUR', codEmpresa: '00000' },
        { code: '112', label: 'EMPLOYE DE BUREAU', codEmpresa: '00000' },
        { code: '113', label: 'TECHNICIEN', codEmpresa: '00000' },
        { code: '114', label: 'TRAVAILLEUR AUTONOME', codEmpresa: '00000' },
        { code: '115', label: 'ACHETEUR', codEmpresa: '00000' },
        { code: '116', label: 'INFORMATICIEN', codEmpresa: '00000' },
        { code: '117', label: 'ETALAGISTE', codEmpresa: '00000' },
        { code: '118', label: 'PHARMACIEN', codEmpresa: '00000' },
        { code: '119', label: 'GARGOTIERE', codEmpresa: '00000' },
        { code: '120', label: 'TAILLEUR', codEmpresa: '00000' },
        { code: '121', label: 'FERAILLEUR', codEmpresa: '00000' },
        { code: '122', label: 'MACON', codEmpresa: '00000' },
        { code: '123', label: 'SALARIE SECT. PRIVE', codEmpresa: '00000' },
        { code: '124', label: 'MILITAIRE', codEmpresa: '00000' },
        { code: '125', label: 'GENDARME', codEmpresa: '00000' },
        { code: '126', label: 'POLICIER', codEmpresa: '00000' },
        { code: '127', label: 'DOUANIER', codEmpresa: '00000' },
        { code: '128', label: 'CAMBISTE', codEmpresa: '00000' },
        { code: '129', label: 'TRANSITEUR', codEmpresa: '00000' },
        { code: '130', label: 'COMPTABLE', codEmpresa: '00000' },
        { code: '131', label: 'ENSEIGNANT', codEmpresa: '00000' },
        { code: '132', label: 'MEDECIN', codEmpresa: '00000' },
        { code: '133', label: 'SAGE FEMME', codEmpresa: '00000' },
        { code: '134', label: 'MATRONE', codEmpresa: '00000' },
        { code: '135', label: 'AGENT TECH. DE SANTE', codEmpresa: '00000' },
        { code: '136', label: 'TOLIER', codEmpresa: '00000' },
        { code: '137', label: 'SOUDEUR', codEmpresa: '00000' },
        { code: '138', label: 'MENUISIER', codEmpresa: '00000' },
        { code: '139', label: 'PEINTRE', codEmpresa: '00000' },
        { code: '140', label: 'JUGE', codEmpresa: '00000' },
        { code: '141', label: 'AVOCAT', codEmpresa: '00000' },
        { code: '142', label: 'SCULPTEUR', codEmpresa: '00000' },
        { code: '143', label: 'ARTISTE', codEmpresa: '00000' },
        { code: '144', label: 'ARCHITECTE', codEmpresa: '00000' },
        { code: '145', label: 'ELECTRICIEN', codEmpresa: '00000' },
        { code: '146', label: 'PHOTOGRAPHE', codEmpresa: '00000' },
        { code: '147', label: 'FORGERON', codEmpresa: '00000' },
        { code: '998', label: 'BIJOUTIER', codEmpresa: '00000' },
        { code: '999', label: 'AUTRES PROFESSIONS', codEmpresa: '00000' }
    ];

    // Types de pièces d'identité
    static readonly ID_TYPES: ReferenceOption[] = [
        { code: '101', label: "N° CARTE D'IDENTITE NATIONALE", codEmpresa: '00000' },
        { code: '102', label: 'N° PASSEPORT', codEmpresa: '00000' },
        { code: '103', label: 'N° PERMIS DE CONDUIRE', codEmpresa: '00000' },
        { code: '104', label: "N° CARTE D'IDENTITE SCOLAIRE", codEmpresa: '00000' },
        { code: '105', label: 'NUMERO MATRICULE', codEmpresa: '00000' },
        { code: '106', label: 'NUMERO DU RCCM', codEmpresa: '00000' },
        { code: '107', label: "N° CARTE D'ELECTEUR", codEmpresa: '00000' },
        { code: '108', label: 'NUMERO TELEPHONE', codEmpresa: '00000' },
        { code: '109', label: 'N° IDENTIFICATION NATIONALE (NIN)', codEmpresa: '00000' },
        { code: '110', label: "N° CARTE AUTRE D' CARTE D'ID", codEmpresa: '00000' },
        { code: '111', label: "N° CARTE D'IDENTITE NLE BIOMETRIQUE", codEmpresa: '00000' }
    ];

    // Provinces
    static readonly PROVINCES: ReferenceOption[] = [
        { code: '101', label: 'CONAKRY' },
        { code: '102', label: 'BEYLA' },
        { code: '103', label: 'BOFFA' },
        { code: '104', label: 'BOKE' },
        { code: '105', label: 'COYAH' },
        { code: '106', label: 'DABOLA' },
        { code: '107', label: 'DALABA' },
        { code: '108', label: 'DINGUIRAYE' },
        { code: '109', label: 'DUBREKA' },
        { code: '110', label: 'FARANAH' },
        { code: '111', label: 'FORECARIAH' },
        { code: '112', label: 'FRIA' },
        { code: '113', label: 'GAOUAL' },
        { code: '114', label: 'GUECKEDOU' },
        { code: '115', label: 'KANKAN' },
        { code: '116', label: 'KEROUANE' },
        { code: '117', label: 'KINDIA' },
        { code: '118', label: 'KISSIDOUGOU' },
        { code: '119', label: 'KOUBIA' },
        { code: '120', label: 'KOUNDARA' },
        { code: '121', label: 'KOUROUSSA' },
        { code: '122', label: 'LABE' },
        { code: '123', label: 'LELOUMA' },
        { code: '124', label: 'LOLA' },
        { code: '125', label: 'MACENTA' },
        { code: '126', label: 'MALI' },
        { code: '127', label: 'MAMOU' },
        { code: '128', label: 'MANDIANA' },
        { code: '129', label: "N'ZEREKORE" },
        { code: '130', label: 'PITA' },
        { code: '131', label: 'SIGUIRI' },
        { code: '132', label: 'TELIMELE' },
        { code: '133', label: 'TOUGUE' },
        { code: '134', label: 'YOMOU' }
    ];

    // Get districts by province
    static getDistrictsByProvince(provinceCode: string): ReferenceOption[] {
        const districtsByProvince: { [key: string]: ReferenceOption[] } = {
            '101': [
                // Kaloum
                { code: '301', label: 'ALMAMYA I' },
                { code: '302', label: 'ALMAMYA II' },
                { code: '303', label: 'BOULBINET' },
                { code: '304', label: 'CORONTHIE I' },
                { code: '305', label: 'CORONTHIE II' },
                { code: '306', label: 'KASSA' },
                { code: '307', label: 'KOULEWONDY' },
                { code: '308', label: 'MANQUEPAS' },
                { code: '309', label: 'SANDERVALIA' },
                { code: '310', label: 'SANS FIL' },
                { code: '311', label: 'TAMARA' },
                { code: '312', label: 'TEMINETAYE' },
                { code: '313', label: 'TOMBO 1' },
                { code: '314', label: 'TOMBO 2' },

                // Dixinn
                { code: '301', label: 'DIXINN CENTRE I' },
                { code: '302', label: 'DIXINN CENTRE II' },
                { code: '303', label: 'DIXINN GARE' },
                { code: '304', label: 'DIXINN GARE RAILS' },
                { code: '305', label: 'DIXINN MOSQUEE' },
                { code: '306', label: 'DIXINN PORT' },
                { code: '307', label: 'BELLE VUE ECOLE' },
                { code: '308', label: 'BELLE VUE MARCHE I' },
                { code: '309', label: 'BELLE VUE MARCHE II' },
                { code: '310', label: 'CAMAYENNE' },
                { code: '311', label: 'CAMEROUN' },
                { code: '312', label: "HAFIA CHATEAU D'EAU" },
                { code: '313', label: 'HAFIA I' },
                { code: '314', label: 'HAFIA II' },
                { code: '315', label: 'HAFIA III' },
                { code: '316', label: 'HAFIA MINIERE I' },
                { code: '317', label: 'HAFIA MINIERE II' },
                { code: '318', label: 'HAFIA MINIERE CENTRE' },
                { code: '319', label: 'HAFIA MOSQUEE' },
                { code: '320', label: 'KENIEN' },
                { code: '321', label: 'LANDREAH' },
                { code: '322', label: 'MINIERE CITE' },

                // Matam
                { code: '301', label: 'C.U MATAM' },
                { code: '302', label: 'MAFANCO CENTRE' },
                { code: '303', label: 'MATAM LIDO' },
                { code: '304', label: 'BONFI' },
                { code: '305', label: 'BONFI MARCHE' },
                { code: '306', label: 'BONFI ROUTIERE' },
                { code: '307', label: 'BOUSSOURA' },
                { code: '308', label: 'CARRIERE CENTRE' },
                { code: '309', label: 'CARRIERE CITE' },
                { code: '310', label: 'COLEAH CENTRE' },
                { code: '311', label: 'COLEAH CITE' },
                { code: '312', label: 'COLEAH DOMINO' },
                { code: '313', label: 'COLEAH IMPRIMERIE' },
                { code: '314', label: 'HERMAKONON MOSQUEE' },
                { code: '315', label: 'HERMAKONON PERMANANCE' },
                { code: '316', label: 'LANSEBOUNDJI' },
                { code: '317', label: 'MOSQUEE BADIA' },
                { code: '318', label: 'MADINA CENTRE' },
                { code: '319', label: 'MADINA CITE (SIG)' },
                { code: '320', label: 'MADINA MARCHE' },
                { code: '321', label: 'MADINA MOSQUEE' },
                { code: '322', label: 'MADINA ECOLE' },
                { code: '323', label: 'MAFANCO' },
                { code: '324', label: 'TOUGUIWONDY' },

                // Ratoma
                { code: '301', label: 'C.U DE RATOMA' },
                { code: '302', label: 'RATOMA DISPENSAIRE' },
                { code: '303', label: 'BANTOUNKA I' },
                { code: '304', label: 'BANTOUNKA II' },
                { code: '305', label: 'DAR ES SALAM I' },
                { code: '306', label: 'DAR ES SALAM II' },
                { code: '307', label: 'HAMDALLAYE I' },
                { code: '308', label: 'HAMDALLAYE II' },
                { code: '309', label: 'HAMDALLAYE MOSQUEE' },
                { code: '310', label: 'KAPORO CENTRE' },
                { code: '311', label: 'KAPORO RAILS' },
                { code: '312', label: 'KIPE' },
                { code: '313', label: 'KOBAYA' },
                { code: '314', label: 'KOLOMA I' },
                { code: '315', label: 'KOLOMA II' },
                { code: '316', label: 'LAMBANYI' },
                { code: '317', label: 'NASROULLAYE' },
                { code: '318', label: 'NASROULAYE I' },
                { code: '319', label: 'NONGO' },
                { code: '320', label: 'NONGO TADY' },
                { code: '321', label: 'SIMBAYA GARE' },
                { code: '322', label: 'SOLOPRIMO' },
                { code: '323', label: 'SONFONIA CENTRE I' },
                { code: '324', label: 'SONFONIA CENTRE II' },
                { code: '325', label: 'SONFONIA GARE I' },
                { code: '326', label: 'BARKAYANKE' },
                { code: '327', label: 'SONFONIA GARE II' },
                { code: '328', label: 'SOUMABOSSIA' },
                { code: '329', label: 'TAOUYAH' },
                { code: '330', label: 'WANINDARA I' },
                { code: '331', label: 'WANINDARA II' },
                { code: '332', label: 'WANINDARA III' },
                { code: '333', label: 'WAREYA' },
                { code: '334', label: 'YATTAYA CENTRE' },
                { code: '335', label: 'YATTAYA FOSSEDE' },
                { code: '336', label: 'YEMBEYA SECTEUR' },
                { code: '337', label: 'BAMBETO CENTRE' },
                { code: '342', label: 'KIROTY' },

                // Matoto
                { code: '301', label: 'C.U DE MATOTO' },
                { code: '302', label: 'MATOTO KHABITAYA' },
                { code: '303', label: 'MATOTO MARCHE' },
                { code: '304', label: 'BEHANZIN' },
                { code: '305', label: 'CAMP ALPHA YAYA DIALLO' },
                { code: '306', label: "CITE DE L'AIR" },
                { code: '307', label: 'DABOMPA' },
                { code: '308', label: 'DABOMPA PLATEAU' },
                { code: '309', label: 'DABONDY ECOLE' },
                { code: '310', label: 'DABONDY I' },
                { code: '311', label: 'DABONDY II' },
                { code: '312', label: 'DABONDY III' },
                { code: '313', label: 'DABONDY' },
                { code: '314', label: 'DAR ES SALAM I' },
                { code: '315', label: 'ENTA MARCHE' },
                { code: '316', label: 'GBESSIA CENTRE' },
                { code: '317', label: 'GBESSIA CITE' },
                { code: '318', label: 'GBESSIA CITE I' },
                { code: '319', label: 'GBESSIA CITE II' },
                { code: '320', label: 'GBESSIA CITE III' },
                { code: '321', label: 'GBESSIA PORT I' },
                { code: '322', label: 'GBESSIA PORT II' },
                { code: '323', label: 'KISSOSSO' },
                { code: '324', label: 'KISSOSSO PLATEAU' },
                { code: '325', label: 'LANSANAYA' },
                { code: '326', label: 'SANGOYA MARCHE' },
                { code: '327', label: 'SANGOYA MOSQUEE' },
                { code: '328', label: 'SIMBAYA ECOLE' },
                { code: '329', label: 'SIMBAYA I' },
                { code: '330', label: 'SIMBAYA II' },
                { code: '331', label: 'TANENE MARCHE' },
                { code: '332', label: 'TANENE MOSQUEE' },
                { code: '333', label: 'TOMBOLIA' },
                { code: '334', label: 'TOMBOLIA PLATEAU' },
                { code: '335', label: 'YIMBAYA ECOLE' },
                { code: '336', label: 'YIMBAYA PERMANENCE' },
                { code: '337', label: 'YIMBAYA PORT' },
                { code: '338', label: 'YIMBAYA TANERIE' },
                { code: '339', label: 'ENTA NORD' },
                { code: '340', label: 'ENTA WASSAWASSA' },
                { code: '341', label: 'ENTA PASSA' },

                // Autres localités
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '102': [
                // BEYLA (C.U DE BEYLA)
                { code: '301', label: 'C.U DE BEYLA' },
                { code: '302', label: 'BANANKORO' },
                { code: '303', label: 'DABADOU' },
                { code: '304', label: 'DIAKOLIDOU SOBAKONON' },
                { code: '305', label: 'DIAKOLIDOU TININKAN' },
                { code: '306', label: 'DRAME OUMAR' },
                { code: '307', label: 'FEREBORY CAMARA' },
                { code: '308', label: 'KEME BOUREMA' },
                { code: '309', label: 'KISSIBOU' },
                { code: '310', label: 'KOIMORIDOU' },
                { code: '311', label: 'MORY SANGAREDOU' },
                { code: '312', label: 'SAMORY TOURE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // BOOLA
                { code: '301', label: 'C.R DE BOOLA' },
                { code: '302', label: 'BOOLA I' },
                { code: '303', label: 'BOOLA II' },
                { code: '304', label: 'BRIKOIDOU' },
                { code: '305', label: 'DIABAMORIDOU' },
                { code: '306', label: 'FOUAMA' },
                { code: '307', label: 'KOIDOU' },
                { code: '308', label: 'OUENZOU' },
                { code: '309', label: 'SAOUSSOUDOU' },
                { code: '310', label: 'SIBAMOU' },
                { code: '311', label: 'YAPANGAYE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // SINKO
                { code: '301', label: 'C.R DE SINKO' },
                { code: '302', label: 'BELEKORO' },
                { code: '303', label: 'BENGOA' },
                { code: '304', label: 'BIRAMADOU BADA' },
                { code: '305', label: 'BOKEMESSEN' },
                { code: '306', label: 'BRONKEDOU' },
                { code: '307', label: 'DIANI' },
                { code: '308', label: 'HERMAKONON' },
                { code: '309', label: 'KONDELA' },
                { code: '310', label: 'KOULOUNDOU' },
                { code: '311', label: 'LUMUMBA' },
                { code: '312', label: 'MBALIA' },
                { code: '313', label: 'MOAKI I' },
                { code: '314', label: 'NAFAYA' },
                { code: '315', label: 'NGOMANDOU' },
                { code: '316', label: 'MKRUMAH' },
                { code: '317', label: 'OUSSOUMORIDOU' },
                { code: '318', label: 'SABOUYA' },
                { code: '319', label: 'SIRIYA' },
                { code: '320', label: 'SORIDOU' },
                { code: '321', label: 'SUE' },
                { code: '322', label: 'TOUMANIDOU' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // MOUSADOU
                { code: '301', label: 'C.R DE MOUSADOU' },
                { code: '302', label: 'DIAKORO' },
                { code: '303', label: 'FAMOILA' },
                { code: '304', label: 'FROMARO' },
                { code: '305', label: 'SIDIKIDOU' },
                { code: '306', label: 'SUELO' },
                { code: '307', label: 'WANINO' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // DIARRAGUERELA
                { code: '301', label: 'C.R DE DIARRAGUERELA' },
                { code: '302', label: 'DOUBADOU' },
                { code: '303', label: 'DOUGBELA' },
                { code: '304', label: 'FEREBORIDOU' },
                { code: '305', label: 'TOUBAKOUNO' },
                { code: '306', label: 'VAFEREDOU' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // NIONSOMORIDOU
                { code: '301', label: 'C.R DE NIONSOMORIDOU' },
                { code: '302', label: 'KEKOURADOU' },
                { code: '303', label: 'KISSIBOULA' },
                { code: '304', label: 'MAFINDOU' },
                { code: '305', label: 'MORIBADOU I' },
                { code: '306', label: 'MORIBADOU II' },
                { code: '307', label: 'SONDOU' },
                { code: '308', label: 'YENTEDOU' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // DIASSADOU
                { code: '301', label: 'C.R DE DIASSADOU' },
                { code: '302', label: 'BEMBEYA' },
                { code: '303', label: 'DIARADOU' },
                { code: '304', label: 'SORIBADOU' },
                { code: '305', label: 'TANGODOU' },
                { code: '306', label: 'WANZONA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // FOUALA
                { code: '301', label: 'C.R DE FOUALA' },
                { code: '302', label: 'ALLAMADOU' },
                { code: '303', label: 'FARABANA' },
                { code: '304', label: 'MALEDOU' },
                { code: '305', label: 'ZOGBODOU' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // GBESSOBA
                { code: '301', label: 'C.R DE GBESSOBA' },
                { code: '302', label: 'BIRAMADOU' },
                { code: '303', label: 'BLANGBA' },
                { code: '304', label: 'DJEMENIN' },
                { code: '305', label: 'DJIFFA' },
                { code: '306', label: 'FAKOUROUSSO' },
                { code: '307', label: 'FONODOU' },
                { code: '308', label: 'MANGBA' },
                { code: '309', label: 'MOUGNEDOU' },
                { code: '310', label: 'SEYA' },
                { code: '311', label: 'TANANTOU' },
                { code: '312', label: 'TINKORO' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KOUMANDOU
                { code: '301', label: 'C.R DE KOUMANDOU' },
                { code: '302', label: 'BELEKOKO' },
                { code: '303', label: 'DJEMOU' },
                { code: '304', label: 'FAMORODOU' },
                { code: '305', label: 'SAARAN' },
                { code: '306', label: 'TOGOBALA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // GBACKEDOU
                { code: '301', label: 'C.R DE GBACKEDOU' },
                { code: '302', label: 'BROMADOU' },
                { code: '303', label: 'DIAKOFOMODOU' },
                { code: '304', label: 'FOUARO' },
                { code: '305', label: 'KAFOBARO' },
                { code: '306', label: 'KOUBEDOU' },
                { code: '307', label: 'MISSIBORO' },
                { code: '308', label: 'MORIDOU' },
                { code: '309', label: 'SANGBANDOU' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // SAMANA
                { code: '301', label: 'C.R DE SAMANA' },
                { code: '302', label: 'DJIBADOU' },
                { code: '303', label: 'FAKOUROUDOU' },
                { code: '304', label: 'KOBALA' },
                { code: '305', label: 'SINEDOU' },
                { code: '306', label: 'SOGBORO' },
                { code: '307', label: 'SOKODOU' },
                { code: '308', label: 'TAMANKO' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KARALA
                { code: '301', label: 'C.R DE KARALA' },
                { code: '302', label: 'DORELA' },
                { code: '303', label: 'GBONA' },
                { code: '304', label: 'KARALA I' },
                { code: '305', label: 'KARALA II' },
                { code: '306', label: 'KOBALA' },
                { code: '307', label: 'WORO' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // SOKOURALA
                { code: '301', label: 'C.R DE SOKOURALA' },
                { code: '302', label: 'FROMARO' },
                { code: '303', label: 'TANANTOU' },
                { code: '304', label: 'WOROCIA' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '103': [
                // BOFFA (C.U. DE BOFFA)
                { code: '301', label: 'C.U. DE BOFFA' },
                { code: '302', label: 'ALMAMYA I' },
                { code: '303', label: 'ALMAMYA II' },
                { code: '304', label: 'BALANDOUGOU' },
                { code: '305', label: 'BOLONDE I' },
                { code: '306', label: 'BOLONDE II' },
                { code: '307', label: 'DAR-ES-SALAM' },
                { code: '308', label: 'DOBIRET' },
                { code: '309', label: 'DOMINGHIA' },
                { code: '310', label: 'FARENGHIA' },
                { code: '311', label: 'KHATIA' },
                { code: '312', label: 'KOSSINSSING' },
                { code: '313', label: 'LAKHATA' },
                { code: '314', label: 'LONKING' },
                { code: '315', label: 'KOUMBOUYA' },
                { code: '316', label: 'MARARA' },
                { code: '317', label: 'SAKAMA' },
                { code: '318', label: 'SEKHEBADE' },
                { code: '319', label: 'THIA' },
                { code: '320', label: 'TORODOYAH' },
                { code: '321', label: 'WALIA' },
                { code: '322', label: 'WEREYA' },
                { code: '323', label: 'YIMMAYA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // TOUGNIFILY
                { code: '301', label: 'C.R DE TOUGNIFILY' },
                { code: '302', label: 'BRIKA' },
                { code: '303', label: 'DIOGOYA' },
                { code: '304', label: 'FONFO' },
                { code: '305', label: 'FOULAYAH' },
                { code: '306', label: 'KALEKALE' },
                { code: '307', label: 'KANTELY' },
                { code: '308', label: 'KHANTATA' },
                { code: '309', label: 'KHISSILING' },
                { code: '310', label: 'KIFFINDA' },
                { code: '311', label: 'KINYAYA' },
                { code: '312', label: 'MAMYA' },
                { code: '313', label: 'MINTANI' },
                { code: '314', label: 'MONCHON' },
                { code: '315', label: 'NALOUKHOURE' },
                { code: '316', label: 'TAMBAYA' },
                { code: '317', label: 'TANENE' },
                { code: '318', label: 'TOMATA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KOBA
                { code: '301', label: 'C.R DE KOBA' },
                { code: '302', label: 'BANGOUYA' },
                { code: '303', label: 'BASSENGUE' },
                { code: '304', label: 'BOORO KITO' },
                { code: '305', label: 'DIXINN 1' },
                { code: '306', label: 'DIXINN 2' },
                { code: '307', label: 'DONYA' },
                { code: '308', label: 'KARAMOKHOYA' },
                { code: '309', label: 'KOBARARE' },
                { code: '310', label: 'KONIBALE' },
                { code: '311', label: 'KOTEYA-KITO' },
                { code: '312', label: 'M’BENDIA' },
                { code: '313', label: 'MAKINSSY' },
                { code: '314', label: 'SAYONYA' },
                { code: '315', label: 'SOUGUEBOUNYI' },
                { code: '316', label: 'TABORIAH 1' },
                { code: '317', label: 'TABORIAH 2' },
                { code: '318', label: 'TANENE' },
                { code: '319', label: 'TATEMA' },
                { code: '320', label: 'TINTIMA' },
                { code: '321', label: 'YANGOYA-KITO' },
                { code: '322', label: 'YARAYAH' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // LISSO
                { code: '301', label: 'C.R DE LISSO' },
                { code: '302', label: 'BONDY' },
                { code: '303', label: 'DETEKHOUNDOU-KHOUN' },
                { code: '304', label: 'GOBIDJE' },
                { code: '305', label: 'MISSIRA MORIYA' },
                { code: '306', label: 'N’DANTARY' },
                { code: '307', label: 'MARENTOUDE,' },
                { code: '308', label: 'SENGUELENKHOURE' },
                { code: '309', label: 'TAMALAN' },
                { code: '310', label: 'TOUBA' },
                { code: '311', label: 'WONDETTY' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // TAMITA
                { code: '301', label: 'C.R DE TAMITA' },
                { code: '302', label: 'DONYA' },
                { code: '303', label: 'DOTORET' },
                { code: '304', label: 'FOUTOUBOUNYI' },
                { code: '305', label: 'GANGANTA' },
                { code: '306', label: 'GBASSAYA' },
                { code: '307', label: 'KELEYA' },
                { code: '308', label: 'KHAMBAYA' },
                { code: '309', label: 'KHORIRA' },
                { code: '310', label: 'MISSIRA' },
                { code: '311', label: 'MOURAYA' },
                { code: '312', label: 'SOUMBOUYADI' },
                { code: '313', label: 'YEMBERING' },
                { code: '314', label: 'YENGUISSA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KOLIA-LAMBANYI
                { code: '301', label: 'C.R DE KOLIA-LAMBANYI' },
                { code: '302', label: 'BOOTA' },
                { code: '303', label: 'FAREMA' },
                { code: '304', label: 'FATAGBOLO' },
                { code: '305', label: 'GOBIDJÉ' },
                { code: '306', label: 'KHALO' },
                { code: '307', label: 'KOLIA-TAFORI' },
                { code: '308', label: 'KORERA' },
                { code: '309', label: 'KOUNFA' },
                { code: '310', label: 'LALAFANYÉ' },
                { code: '311', label: 'LONGO' },
                { code: '312', label: 'MADINA-HOUBOU' },
                { code: '313', label: 'MELLEKHOURE' },
                { code: '314', label: 'TAGBE' },
                { code: '315', label: 'YOYAH' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // DOUPROU
                { code: '301', label: 'C.R DE DOUPROU' },
                { code: '302', label: 'BANDEYINDE' },
                { code: '303', label: 'BOUREKHEBADE' },
                { code: '304', label: 'DOUPROU' },
                { code: '305', label: 'KOUKOUDE' },
                { code: '306', label: 'KOUMBAYAH' },
                { code: '307', label: 'KOUNDINDE' },
                { code: '308', label: 'POUKHOUN' },
                { code: '309', label: 'SIRANKA' },
                { code: '310', label: 'SOBANET' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // MANKOUNTAN
                { code: '301', label: 'C.R DE MANKOUNTAN' },
                { code: '302', label: 'BIGORI' },
                { code: '303', label: 'BONGOLON' },
                { code: '304', label: 'DANSI' },
                { code: '305', label: 'KAKALA' },
                { code: '306', label: 'KALEXES' },
                { code: '307', label: 'KATONGORON' },
                { code: '308', label: 'KOLON' },
                { code: '309', label: 'MADIA' },
                { code: '310', label: 'SIBALI' },
                { code: '311', label: 'TOUMBETA' },
                { code: '312', label: 'YAMPONI' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '104': [
                // BOKE (C.U DE BOKE)
                { code: '301', label: 'C.U DE BOKE' },
                { code: '302', label: 'BARALANDE' },
                { code: '303', label: 'CORRERAH' },
                { code: '304', label: 'DIBIA' },
                { code: '305', label: 'DIOUMAYA' },
                { code: '306', label: 'GOREYE' },
                { code: '307', label: 'GUILLERE' },
                { code: '308', label: 'KADIGUIRA' },
                { code: '309', label: 'KOUGNEWADE I' },
                { code: '310', label: 'KOUGNEWADE II' },
                { code: '311', label: 'KOULIFANYA' },
                { code: '312', label: 'LAMBANDJI' },
                { code: '313', label: 'MADINA KEBENYA' },
                { code: '314', label: 'TAMARANSI' },
                { code: '315', label: 'TOMBOYA' },
                { code: '316', label: 'YOMBOYA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KAMSAR
                { code: '301', label: 'C.R DE KAMSAR' },
                { code: '302', label: 'BINARY' },
                { code: '303', label: 'BOTINY' },
                { code: '304', label: 'FILIMA' },
                { code: '305', label: 'KASSONGONY' },
                { code: '306', label: 'KATONGORON' },
                { code: '307', label: 'KAWAS' },
                { code: '308', label: 'KOUFFIN' },
                { code: '309', label: 'TAIGBE' },
                { code: '310', label: 'MADINA BORBOFF' },
                { code: '311', label: 'KAMAKOULOUN' },
                { code: '312', label: 'MISSIRA' },
                { code: '313', label: 'KAKILENSY' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KOLABOUI
                { code: '301', label: 'C.R DE KOLABOUI' },
                { code: '302', label: 'BOKARIYA' },
                { code: '303', label: 'DABANKOU' },
                { code: '304', label: 'DAKONTA' },
                { code: '305', label: 'DIASSIA' },
                { code: '306', label: 'DIAKHABIA' },
                { code: '307', label: 'FODEKONTEYA' },
                { code: '308', label: 'KAMIKOLON' },
                { code: '309', label: 'LEFOUREBOUNYI' },
                { code: '310', label: 'SARABAYA' },
                { code: '311', label: 'SATENENYA' },
                { code: '312', label: 'SOGOBOLI' },
                { code: '313', label: 'SONGOLON' },
                { code: '314', label: 'TABONDEA' },
                { code: '315', label: 'TASSARA' },
                { code: '316', label: 'TASSIBON' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // BINTIMODIYA
                { code: '301', label: 'C.R DE BINTIMODIYA' },
                { code: '302', label: 'GARAMA' },
                { code: '303', label: 'KANKAKO' },
                { code: '304', label: 'KATAKO' },
                { code: '305', label: 'KOFTENDEM' },
                { code: '306', label: 'KOLIA' },
                { code: '307', label: 'LINTANG' },
                { code: '308', label: 'MAREN' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // SANGAREDI
                { code: '301', label: 'C.R DE SANGAREDI' },
                { code: '302', label: 'AYEKOYE' },
                { code: '303', label: 'BALANDOUGOU' },
                { code: '304', label: 'BAPPA SERGENT' },
                { code: '305', label: 'BOULLERE' },
                { code: '306', label: 'GUILDE' },
                { code: '307', label: 'KOURAWEL' },
                { code: '308', label: 'LAVAGE' },
                { code: '309', label: 'SILIDARA' },
                { code: '310', label: 'SOUKA' },
                { code: '311', label: 'TYANKOUN NAYE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // DABISS
                { code: '301', label: 'C.R DE DABISS' },
                { code: '302', label: 'HAMDALLAYE KABOTT' },
                { code: '303', label: 'KOUDA' },
                { code: '304', label: 'MISSIDE BHOUNDOU' },
                { code: '305', label: 'LENGUE' },
                { code: '306', label: 'NIAMAYARAWOL' },
                { code: '307', label: 'PARABOLE' },
                { code: '308', label: 'SYLIKONKO' },
                { code: '309', label: 'TOMBOYA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KANFARANDE
                { code: '301', label: 'C.R DE KANFARANDE' },
                { code: '302', label: 'BOFFA - DAR' },
                { code: '303', label: 'DABRIBON' },
                { code: '304', label: 'DOBALI' },
                { code: '305', label: 'KADIGNE' },
                { code: '306', label: 'KALAGBA' },
                { code: '307', label: 'KAMBILAN' },
                { code: '308', label: 'KAPKIN' },
                { code: '309', label: 'KAPSINI' },
                { code: '310', label: 'KASMACK' },
                { code: '311', label: 'KATFOURA' },
                { code: '312', label: 'KIBANCO' },
                { code: '313', label: 'KOUKOUBA' },
                { code: '314', label: 'LANSANAYA' },
                { code: '315', label: 'TARIKHOURE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // MALAPOUYAH
                { code: '301', label: 'C.R DE MALAPOUYAH' },
                { code: '302', label: 'BALLA' },
                { code: '303', label: 'DJOLOL' },
                { code: '304', label: 'HAFIA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // SANSALE
                { code: '301', label: 'C.R DE SANSALE' },
                { code: '302', label: 'FIFF' },
                { code: '303', label: 'GALLE TCHOLLA' },
                { code: '304', label: 'SANSALE' },
                { code: '305', label: 'YARGA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // TANENE
                { code: '301', label: 'C.R DE TANENE' },
                { code: '302', label: 'BOUSSOURA' },
                { code: '303', label: 'DAMBANCHAN' },
                { code: '304', label: 'DJIGUITY' },
                { code: '305', label: 'KABOYE' },
                { code: '306', label: 'KATOUGOUMA' },
                { code: '307', label: 'KIMIYA' },
                { code: '308', label: 'KINTAOU DACONTA' },
                { code: '309', label: 'NDANGARA' },
                { code: '310', label: 'Kintaou Daconta' },
                { code: '311', label: 'Ndangara' },
                { code: '312', label: 'Tanènè Centre' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '105': [
                // COYAH (C.U DE COYAH)
                { code: '301', label: 'C.U DE COYAH' },
                { code: '302', label: 'BATOUYAH' },
                { code: '303', label: 'CENTRE' },
                { code: '304', label: 'DOUMBOUYAH ALKHALY' },
                { code: '305', label: 'SEYDOUYA' },
                { code: '306', label: 'DOUMBOUYAH CENTRE' },
                { code: '307', label: 'DOUMBOUYAH ECOLE' },
                { code: '308', label: 'FILY 1' },
                { code: '309', label: 'FILY 2' },
                { code: '310', label: 'KAROUBA' },
                { code: '311', label: 'KM 54' },
                { code: '312', label: 'LABHO' },
                { code: '313', label: 'LAMINAYAH' },
                { code: '314', label: 'NAKIRY' },
                { code: '315', label: 'NORD 1' },
                { code: '316', label: 'NORD 2' },
                { code: '317', label: 'SOMAYAH CENTRE' },
                { code: '318', label: 'SOMAYAH FORY' },
                { code: '319', label: 'SOMAYAH MOSQUÉE' },
                { code: '320', label: 'SOMAYAH PLATEAU' },
                { code: '321', label: 'TOUGANDE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // MANEAH
                { code: '301', label: 'C.R DE MANEAH' },
                { code: '302', label: 'BAMBAYAH' },
                { code: '303', label: 'BENTOURAYAH PLATEAU' },
                { code: '304', label: 'BENTOURAYAH VILLAGE' },
                { code: '305', label: 'C B C SUD' },
                { code: '306', label: 'FASSIAH CENTRE' },
                { code: '307', label: 'FASSIAH TEXTILE' },
                { code: '308', label: 'FRIGUIADY NORD' },
                { code: '309', label: 'FRIGUIADY SUD' },
                { code: '310', label: 'HEREMAKONO' },
                { code: '311', label: 'KALOKHOYAH' },
                { code: '312', label: 'KASSOGNAH' },
                { code: '313', label: 'KOUNTIA NORD' },
                { code: '314', label: 'KOUNTIA VILLAGE' },
                { code: '315', label: 'SANOYAH KM36' },
                { code: '316', label: 'SANOYAH RAILS' },
                { code: '317', label: 'DISPENSAIRE' },
                { code: '318', label: 'SANOYAH RAILS PLATEAU' },
                { code: '319', label: 'TANENE 1' },
                { code: '320', label: 'TANENE 2' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // WONKIFONG
                { code: '301', label: 'C.R DE WONKIFONG' },
                { code: '302', label: 'BALAMODIA' },
                { code: '303', label: 'BALLAYA' },
                { code: '304', label: 'BONFET' },
                { code: '305', label: 'DONEAH' },
                { code: '306', label: 'KENDOUMAYAH' },
                { code: '307', label: 'KIRIAH' },
                { code: '308', label: 'KOUNSOUTA' },
                { code: '309', label: 'KOUYEYA' },
                { code: '310', label: 'LAMINAYAH 970' },
                { code: '311', label: 'MANGATA' },
                { code: '312', label: 'NASSER' },
                { code: '313', label: 'TAMBAYAH' },
                { code: '314', label: 'TOGUIRON' },
                { code: '315', label: 'YENGUIAKHORY' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KOURIA
                { code: '301', label: 'C.R DE KOURIA' },
                { code: '302', label: 'BANGOUYAH' },
                { code: '303', label: 'GOLEAH' },
                { code: '304', label: 'KOBA' },
                { code: '305', label: 'KOLAKHOURE' },
                { code: '306', label: 'KOURIA CENTRE' },
                { code: '307', label: 'MORIAKHORY' },
                { code: '308', label: 'TABILY' },
                { code: '309', label: 'TANENE FRIBADE' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '106': [
                // DABOLA (C.U DE DABOLA)
                { code: '301', label: 'C.U DE DABOLA' },
                { code: '302', label: 'BABILIA' },
                { code: '303', label: 'BANIRÉ' },
                { code: '304', label: 'DABOLA KORO' },
                { code: '305', label: 'FOUNDENG I' },
                { code: '306', label: 'FOUNDENG II' },
                { code: '307', label: 'HAMDALLAYE' },
                { code: '308', label: 'HEREMAKONO' },
                { code: '309', label: 'KALELA' },
                { code: '310', label: 'KAMBAYA' },
                { code: '311', label: 'SINERY' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // BANKO
                { code: '301', label: 'C.R DE BANKO' },
                { code: '302', label: 'SANARELAH' },
                { code: '303', label: 'NAFADJI' },
                { code: '304', label: 'HERMAKONO' },
                { code: '305', label: 'DALADO' },
                { code: '306', label: 'MORIBEYA' },
                { code: '307', label: 'KEBEYAH 1' },
                { code: '308', label: 'KEBEYAH 2' },
                { code: '309', label: 'BANDANKELIN' },
                { code: '310', label: 'BADINKO' },
                { code: '311', label: 'DIABARIDALADO' },
                { code: '312', label: 'NIANDAN' },
                { code: '313', label: 'KALELA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // ARFAMOUSSAYAH
                { code: '301', label: 'C.R DE ARFAMOUSSAYAH' },
                { code: '302', label: 'DARO' },
                { code: '304', label: 'FELLA MOSQUEE' },
                { code: '305', label: 'FELLE HAMDALLAYE' },
                { code: '306', label: 'FADAMA' },
                { code: '307', label: 'KOOLO' },
                { code: '308', label: 'KALAKO' },
                { code: '309', label: 'WALISSA' },
                { code: '310', label: 'NIALEN' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // DOGOMET
                { code: '301', label: 'C.R DE DOGOMET' },
                { code: '302', label: 'DABOLA BERETE' },
                { code: '303', label: 'FELLO NDIANDY' },
                { code: '304', label: 'KANKAN FODEYA' },
                { code: '305', label: 'KOBOLONIA' },
                { code: '306', label: 'SARIFOULA BAFING' },
                { code: '307', label: 'SEGUEYA' },
                { code: '308', label: 'TOTIYA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // BISSIKRIMA
                { code: '301', label: 'C.R DE BISSIKRIMA' },
                { code: '302', label: 'HAMDALLAYE' },
                { code: '303', label: 'KAMBAYA' },
                { code: '304', label: 'KANKAN FODEYA' },
                { code: '305', label: 'KOLON' },
                { code: '306', label: 'LOPPÈ' },
                { code: '307', label: 'SAMPOLIA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KONENDOU
                { code: '301', label: 'C.R DE KONENDOU' },
                { code: '302', label: 'DANDAKARA' },
                { code: '303', label: 'KONENDOU 1' },
                { code: '304', label: 'KONENDOU 2' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // N’DEMA
                { code: '301', label: 'C.R DE N’DEMA' },
                { code: '302', label: 'DIABAKANIA' },
                { code: '303', label: 'FINALA' },
                { code: '304', label: 'KONSO' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KANKAMA
                { code: '301', label: 'C.R DE KANKAMA' },
                { code: '302', label: 'BOUKA DOUNKIDO' },
                { code: '303', label: 'DIGUILIN MANINKA' },
                { code: '304', label: 'SAKOLA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KINDOYE
                { code: '301', label: 'C.R DE KINDOYE' },
                { code: '302', label: 'KINDOYE I' },
                { code: '303', label: 'KINDOYE II' },
                { code: '304', label: 'SARIFOULA' },
                { code: '305', label: 'TIGUISSAN' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '107': [
                // DALABA (C.U DE DALABA)
                { code: '301', label: 'C.U DE DALABA' },
                { code: '302', label: 'DALABA MISSIDE' },
                { code: '303', label: 'DAR ES SALAM' },
                { code: '304', label: 'DIAGUISSA' },
                { code: '305', label: 'HERAMAKONON' },
                { code: '306', label: 'KOLLANGUEL' },
                { code: '307', label: 'PELLEL YERO' },
                { code: '308', label: 'SILY' },
                { code: '309', label: 'TANGAMA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // DITINN
                { code: '301', label: 'C.R DE DITINN' },
                { code: '302', label: 'BOTOBOFEL' },
                { code: '303', label: 'DIAMBOURIYA' },
                { code: '304', label: 'FOUGOUMBA' },
                { code: '305', label: 'KOUROU' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KANKALABE
                { code: '301', label: 'C.R DE KANKALABE' },
                { code: '302', label: 'DIAWLEKO' },
                { code: '303', label: 'DONGHOL' },
                { code: '304', label: 'GOBIRE' },
                { code: '305', label: 'KOUFFA' },
                { code: '306', label: 'NDANTABA' },
                { code: '307', label: 'SEFOURE' },
                { code: '308', label: 'TIORO' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // MITTY
                { code: '301', label: 'C.R DE MITTY' },
                { code: '302', label: 'BINDI' },
                { code: '303', label: 'DIANGOLO' },
                { code: '304', label: 'DJIGUIWEL' },
                { code: '305', label: 'FONFOYA' },
                { code: '306', label: 'LELATO' },
                { code: '307', label: 'PARAWI' },
                { code: '308', label: 'PETTY' },
                { code: '309', label: 'SEBHORY' },
                { code: '310', label: 'YALAGUE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // MOMBEYAH
                { code: '301', label: 'C.R DE MOMBEYAH' },
                { code: '302', label: 'DOUGAYA' },
                { code: '303', label: 'DOUNKI' },
                { code: '304', label: 'FOGO' },
                { code: '305', label: 'GALI' },
                { code: '306', label: 'GNEKEMA' },
                { code: '307', label: 'HAFIA' },
                { code: '308', label: 'KENENE' },
                { code: '309', label: 'KIGNA' },
                { code: '310', label: 'AUTRES LOCALITES' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KAALAN
                { code: '301', label: 'C.R DE KAALAN' },
                { code: '302', label: 'HERIKO' },
                { code: '303', label: 'KOLLAKOYE' },
                { code: '304', label: 'KOYIN HENERE' },
                { code: '305', label: 'NDANTARI' },
                { code: '306', label: 'PELLAL' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // BODIE
                { code: '301', label: 'C.R DE BODIE' },
                { code: '302', label: 'BOUROUWAL DAOUBHE' },
                { code: '303', label: 'MANTA' },
                { code: '304', label: 'MARANDA' },
                { code: '305', label: 'MBOURO' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KEBALY
                { code: '301', label: 'C.R DE KEBALY' },
                { code: '302', label: 'BANGA' },
                { code: '303', label: 'BOUSSOURA' },
                { code: '304', label: 'DJOURIYA' },
                { code: '305', label: 'HERIKO' },
                { code: '306', label: 'KAHEL' },
                { code: '307', label: 'MIRIRE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KOBA
                { code: '301', label: 'C.R DE KOBA' },
                { code: '302', label: 'FELLO MALANGA' },
                { code: '303', label: 'HAFIA' },
                { code: '304', label: 'HAFIA KOKOU' },
                { code: '305', label: 'HOLLANDE' },
                { code: '306', label: 'HOORE DJOLY' },
                { code: '307', label: 'KAAKORI' },
                { code: '308', label: 'LEELE' },
                { code: '309', label: 'LOOPE' },
                { code: '310', label: 'TYEWNGOL' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // MAFARA
                { code: '301', label: 'C.R DE MAFARA' },
                { code: '302', label: 'DONDE' },
                { code: '303', label: 'KETIGUIYA' },
                { code: '304', label: 'PENNOUN' },
                { code: '305', label: 'SERIYABHE' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '108': [
                // DINGUIRAYE (C.U DE DINGUIRAYE)
                { code: '301', label: 'C.U DE DINGUIRAYE' },
                { code: '302', label: 'BALLAGNOUMAYA' },
                { code: '303', label: 'BHOURIA' },
                { code: '304', label: 'HELLAYABHE' },
                { code: '305', label: 'KAMBAN AINDE' },
                { code: '306', label: 'KAMBAN SABE' },
                { code: '307', label: 'KEBALY' },
                { code: '308', label: 'KOUBI LEY SERE' },
                { code: '309', label: 'KOUMBIA LEY FELLO' },
                { code: '310', label: 'KOUROULA' },
                { code: '311', label: 'LANKON' },
                { code: '312', label: 'MANDEN' },
                { code: '313', label: 'PARADJI' },
                { code: '314', label: 'PARAWOL DJAGUI' },
                { code: '315', label: 'SEBEKORO' },
                { code: '316', label: 'TINKISSO' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // DIALAKORO
                { code: '301', label: 'C.R DE DIALAKORO' },
                { code: '302', label: 'DAR-ES-SALAM' },
                { code: '303', label: 'DIALAKORO CENTRE' },
                { code: '304', label: 'FELLO LAMOU' },
                { code: '305', label: 'MOSSOKO' },
                { code: '306', label: 'SANDANFARA' },
                { code: '307', label: 'WATALA' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // SELOUMA
                { code: '301', label: 'C.R DE SELOUMA' },
                { code: '302', label: 'BOSSERE' },
                { code: '303', label: 'FADIA' },
                { code: '304', label: 'KOBALA' },
                { code: '305', label: 'SELOUMA' },
                { code: '306', label: 'WALA WALA' },
                { code: '307', label: 'WALAN MOSQUEE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // KALINKO
                { code: '301', label: 'C.R DE KALINKO' },
                { code: '302', label: 'BABILA' },
                { code: '303', label: 'BOKOTY' },
                { code: '304', label: 'DIABEREMINY' },
                { code: '305', label: 'DJANKOUROU' },
                { code: '306', label: 'DJISSOUMA' },
                { code: '307', label: 'FARABATO' },
                { code: '308', label: 'FODEKARIA' },
                { code: '309', label: 'KALINKO' },
                { code: '310', label: 'KANSATO' },
                { code: '311', label: 'LEPPY TCHÉWI' },
                { code: '312', label: 'LOUFFA MISSIDE' },
                { code: '313', label: 'MISSIRA' },
                { code: '314', label: 'NIOGO' },
                { code: '315', label: 'SANTANFARA' },
                { code: '316', label: 'WALANDAMA' },
                { code: '317', label: 'YALLAGUERÉ' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // BANORA
                { code: '301', label: 'C.R DE BANORA' },
                { code: '302', label: 'BANORA' },
                { code: '303', label: 'BOUKARIA' },
                { code: '304', label: 'BOUSSOURA' },
                { code: '305', label: 'DARAYILIMALO' },
                { code: '306', label: 'KIGNERO' },
                { code: '307', label: 'KOKOROBANI' },
                { code: '308', label: 'KOLLA' },
                { code: '309', label: 'LOPPE-SOUNTOU' },
                { code: '310', label: 'MATAGANIA' },
                { code: '311', label: 'MBALLOUFARA' },
                { code: '312', label: 'MBONET' },
                { code: '313', label: 'NAFADJI FOULA' },
                { code: '314', label: 'NAFADJI MANINKA' },
                { code: '315', label: 'NDIARENDI' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // DIATIFERE
                { code: '301', label: 'C.R DE DIATIFERE' },
                { code: '302', label: 'DAÏBATOU' },
                { code: '303', label: 'DIATIFERE' },
                { code: '304', label: 'FADOUGOU' },
                { code: '305', label: 'FAMÈRÈ' },
                { code: '306', label: 'FANDANDA' },
                { code: '307', label: 'KALIN' },
                { code: '308', label: 'KARFA' },
                { code: '309', label: 'MAMOUDOUYA 1' },
                { code: '310', label: 'MAMOUDOUYA 2' },
                { code: '311', label: 'NANAKO' },
                { code: '312', label: 'RANGHAYA' },
                { code: '313', label: 'SANKARAN' },
                { code: '314', label: 'SOUBEKINDY' },
                { code: '315', label: 'SOUROU' },
                { code: '316', label: 'SYLLAYA' },
                { code: '317', label: 'WONSON' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // LANSANAYA
                { code: '301', label: 'C.R DE LANSANAYA' },
                { code: '302', label: 'DAYEBHE' },
                { code: '303', label: 'HANSAGUERE' },
                { code: '304', label: 'LANSANAYA' },
                { code: '305', label: 'SANTIGUIYA' },
                { code: '306', label: 'TAMBANORO' },
                { code: '307', label: 'WOUYABHE' },
                { code: '399', label: 'AUTRES LOCALITES' },
                // GAGNAKALY
                { code: '301', label: 'C.R DE GAGNAKALY' },
                { code: '302', label: 'BAGUI' },
                { code: '303', label: 'BELEYA' },
                { code: '304', label: 'BOUSSOURA' },
                { code: '305', label: 'GAGNAKALY' },
                { code: '306', label: 'HERAKO' },
                { code: '307', label: 'KALINKO MISSIRA' },
                { code: '308', label: 'KEYLA' },
                { code: '309', label: 'MISSIRAH' },
                { code: '310', label: 'NOUHOUYA' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '109': [
                // DUBREKA
                { code: '301', label: 'C.U DE DUBREKA' },
                { code: '302', label: 'ANSOUMANIAH' },
                { code: '303', label: 'BAILOBAYA CENTRE' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '110': [
                // FARANAH
                { code: '301', label: 'C.U DE FARANAH' },
                { code: '302', label: 'ABATTOIR I' },
                { code: '303', label: 'ABATTOIR II' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '111': [
                // FORECARIAH
                { code: '301', label: 'C.U DE FORECARIAH' },
                { code: '302', label: 'FATACO I' },
                { code: '303', label: 'FATACO II' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '112': [
                // FRIA
                { code: '301', label: 'C.U DE FRIA' },
                { code: '302', label: 'ALPHA YAYA' },
                { code: '303', label: 'AVIATION I' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '113': [
                // GAOUAL
                { code: '301', label: 'C.U DE GAOUAL' },
                { code: '302', label: 'BARKÈRÈ' },
                { code: '303', label: 'BASSANTO' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '114': [
                // GUECKEDOU
                { code: '301', label: 'C.U DE GUECKEDOU' },
                { code: '302', label: 'BAFILABEN' },
                { code: '303', label: 'BALLADOU' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '115': [
                // KANKAN
                { code: '301', label: 'C.U DE KANKAN' },
                { code: '302', label: 'AVIATION' },
                { code: '303', label: 'BANANKORODA' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '116': [
                // KEROUANE
                { code: '301', label: 'C.U DE KEROUANE' },
                { code: '302', label: 'DIALA' },
                { code: '303', label: 'KAMANDOU' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '117': [
                // KINDIA
                { code: '301', label: 'C.U DE KINDIA' },
                { code: '302', label: 'ABATOIRE 1' },
                { code: '303', label: 'ABATTOIRE 2' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '118': [
                // KISSIDOUGOU
                { code: '301', label: 'C.U DE KISSIDOUGOU' },
                { code: '302', label: 'DAR-ES-SALAM' },
                { code: '303', label: 'DOUNINKONO' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '119': [
                // KOUBIA
                { code: '301', label: 'C.U DE KOUBIA' },
                { code: '302', label: 'BASSARATA' },
                { code: '303', label: 'GORDIO' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '120': [
                // KOUNDARA
                { code: '301', label: 'C.U DE KOUNDARA' },
                { code: '302', label: 'KANDAÏDA' },
                { code: '303', label: 'ATHIABALY' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '121': [
                // KOUROUSSA
                { code: '301', label: 'C.U DE KOUROUSSA' },
                { code: '302', label: 'DIARAGBELA 1' },
                { code: '303', label: 'DIARGBELA 2' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '122': [
                // LABE
                { code: '301', label: 'C.U DE LABE' },
                { code: '302', label: 'BAMBAYA' },
                { code: '303', label: 'COMPAYA' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '123': [
                // LELOUMA
                { code: '301', label: 'C.U DE LELOUMA' },
                { code: '302', label: 'DIALA II' },
                { code: '303', label: 'DIALA MISSIDE' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '124': [
                // LOLA
                { code: '301', label: 'C.U DE LOLA' },
                { code: '302', label: 'BALEMOU' },
                { code: '303', label: 'DOUSSOU (NQ)' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '125': [
                // MACENTA
                { code: '301', label: 'C.U DE MACENTA' },
                { code: '302', label: 'BAMALA' },
                { code: '303', label: 'BANIZE' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '126': [
                // MALI
                { code: '301', label: 'C.U DE MALI' },
                { code: '302', label: 'BANDOUYA' },
                { code: '303', label: 'BARA' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '127': [
                // MAMOU
                { code: '301', label: 'C.U DE MAMOU' },
                { code: '302', label: 'ABATTOIR I' },
                { code: '303', label: 'ABATTOIR II' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '128': [
                // MANDIANA
                { code: '301', label: 'C.U DE MANDIANA' },
                { code: '302', label: 'CHATEAU' },
                { code: '303', label: 'HERMAKONO' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '129': [
                // N'ZEREKORE
                { code: '301', label: "C.U DE N'ZEREKORE" },
                { code: '302', label: 'BELLE VUE' },
                { code: '303', label: 'COMMERCIAL' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '130': [
                // PITA
                { code: '301', label: 'C.U DE PITA' },
                { code: '302', label: 'BENDOUGOU' },
                { code: '303', label: 'DOW SARE' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '131': [
                // SIGUIRI
                { code: '301', label: 'C.U DE SIGUIRI' },
                { code: '302', label: 'BAMBALA' },
                { code: '303', label: 'BOLIBANA I' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '132': [
                // TELIMELE
                { code: '301', label: 'C.U DE TELIMELE' },
                { code: '302', label: 'BAGUIRE' },
                { code: '303', label: 'BARKERE' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '133': [
                // TOUGUE
                { code: '301', label: 'C.U DE TOUGUE' },
                { code: '302', label: 'BALLAMA' },
                { code: '303', label: 'BOLLET' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ],
            '134': [
                // YOMOU
                { code: '301', label: 'C.U DE YOMOU' },
                { code: '302', label: 'GBAMOU' },
                { code: '303', label: 'GBANAHOLY' },
                { code: '399', label: 'AUTRES LOCALITES' }
            ]
        };

        return districtsByProvince[provinceCode] || [];
    }
}
