-- V129 : perimetre du portefeuille credits SAF — correspondance point de service digi <-> agence SAF.
-- La colonne cod_agencia_saf relie chaque pointvente au COD_AGENCIA de SAF2000 (CF_AGENCIAS).
-- Pre-remplissage des correspondances sures (appariement par libelle, referentiel agences CRG
-- transmis par la BCRG le 27/08). Les PS sans correspondance restent NULL : a completer
-- manuellement (requete de controle en fin de fichier).

ALTER TABLE pointvente ADD COLUMN IF NOT EXISTS cod_agencia_saf VARCHAR(10);

COMMENT ON COLUMN pointvente.cod_agencia_saf IS
'COD_AGENCIA SAF2000 du point de service (perimetre du portefeuille credits SAF). NULL = non relie.';

UPDATE pointvente SET cod_agencia_saf = '125' WHERE cod_agencia_saf IS NULL AND libele = 'Albadaria'; -- SAF: ALBADARIAH (inclusion)
UPDATE pointvente SET cod_agencia_saf = '090' WHERE cod_agencia_saf IS NULL AND libele = 'Balandougouba'; -- SAF: BALANDOUGOUBA (exact)
UPDATE pointvente SET cod_agencia_saf = '102' WHERE cod_agencia_saf IS NULL AND libele = 'Banankoro'; -- SAF: BANANKORO (exact)
UPDATE pointvente SET cod_agencia_saf = '097' WHERE cod_agencia_saf IS NULL AND libele = 'Banfelé'; -- SAF: Banfele (exact)
UPDATE pointvente SET cod_agencia_saf = '020' WHERE cod_agencia_saf IS NULL AND libele = 'Bangouyah'; -- SAF: BANGOUYAH (exact)
UPDATE pointvente SET cod_agencia_saf = '119' WHERE cod_agencia_saf IS NULL AND libele = 'Banian'; -- SAF: BANIAN (exact)
UPDATE pointvente SET cod_agencia_saf = '135' WHERE cod_agencia_saf IS NULL AND libele = 'Banko'; -- SAF: BANKO (exact)
UPDATE pointvente SET cod_agencia_saf = '128' WHERE cod_agencia_saf IS NULL AND libele = 'Bardou'; -- SAF: BARDOU (exact)
UPDATE pointvente SET cod_agencia_saf = '013' WHERE cod_agencia_saf IS NULL AND libele = 'Benty'; -- SAF: BENTY (exact)
UPDATE pointvente SET cod_agencia_saf = '142' WHERE cod_agencia_saf IS NULL AND libele = 'Beyla'; -- SAF: BEYLA (exact)
UPDATE pointvente SET cod_agencia_saf = '152' WHERE cod_agencia_saf IS NULL AND libele = 'Bignamou'; -- SAF: BIGNAMOU (exact)
UPDATE pointvente SET cod_agencia_saf = '030' WHERE cod_agencia_saf IS NULL AND libele = 'Bintimodia'; -- SAF: BINTIMODIA (exact)
UPDATE pointvente SET cod_agencia_saf = '025' WHERE cod_agencia_saf IS NULL AND libele = 'Boffa'; -- SAF: BOFFA (exact)
UPDATE pointvente SET cod_agencia_saf = '031' WHERE cod_agencia_saf IS NULL AND libele = 'Boké'; -- SAF: BOKE (exact)
UPDATE pointvente SET cod_agencia_saf = '144' WHERE cod_agencia_saf IS NULL AND libele = 'Boola'; -- SAF: BOOLA (exact)
UPDATE pointvente SET cod_agencia_saf = '153' WHERE cod_agencia_saf IS NULL AND libele = 'Bowé'; -- SAF: BOWE (exact)
UPDATE pointvente SET cod_agencia_saf = '001' WHERE cod_agencia_saf IS NULL AND libele = 'Coyah'; -- SAF: COYAH (exact)
UPDATE pointvente SET cod_agencia_saf = '137' WHERE cod_agencia_saf IS NULL AND libele = 'Dabola'; -- SAF: DABOLA (exact)
UPDATE pointvente SET cod_agencia_saf = '073' WHERE cod_agencia_saf IS NULL AND libele = 'Dalaba'; -- SAF: DALABA (exact)
UPDATE pointvente SET cod_agencia_saf = '103' WHERE cod_agencia_saf IS NULL AND libele = 'Damaro'; -- SAF: DAMARO (exact)
UPDATE pointvente SET cod_agencia_saf = '127' WHERE cod_agencia_saf IS NULL AND libele = 'Dandou'; -- SAF: DANDOU (exact)
UPDATE pointvente SET cod_agencia_saf = '177' WHERE cod_agencia_saf IS NULL AND libele = 'Daro'; -- SAF: DARO (exact)
UPDATE pointvente SET cod_agencia_saf = '140' WHERE cod_agencia_saf IS NULL AND libele = 'Dialakoro'; -- SAF: DIALAKORO (exact)
UPDATE pointvente SET cod_agencia_saf = '151' WHERE cod_agencia_saf IS NULL AND libele = 'Diecke'; -- SAF: DIECKE (exact)
UPDATE pointvente SET cod_agencia_saf = '139' WHERE cod_agencia_saf IS NULL AND libele = 'Dinguiraye'; -- SAF: DINGUIRAYE ET MBONET (inclusion)
UPDATE pointvente SET cod_agencia_saf = '047' WHERE cod_agencia_saf IS NULL AND libele = 'Diountou'; -- SAF: DIOUNTOU (exact)
UPDATE pointvente SET cod_agencia_saf = '074' WHERE cod_agencia_saf IS NULL AND libele = 'Ditinn'; -- SAF: DITINN (exact)
UPDATE pointvente SET cod_agencia_saf = '138' WHERE cod_agencia_saf IS NULL AND libele = 'Dogomet'; -- SAF: DOGOMET (exact)
UPDATE pointvente SET cod_agencia_saf = '106' WHERE cod_agencia_saf IS NULL AND libele = 'Doko'; -- SAF: DOKO (exact)
UPDATE pointvente SET cod_agencia_saf = '054' WHERE cod_agencia_saf IS NULL AND libele = 'Donghol Touma'; -- SAF: DONGHOL TOUMA (exact)
UPDATE pointvente SET cod_agencia_saf = '068' WHERE cod_agencia_saf IS NULL AND libele = 'Dounet'; -- SAF: dounet (exact)
UPDATE pointvente SET cod_agencia_saf = '026' WHERE cod_agencia_saf IS NULL AND libele = 'Douprou'; -- SAF: DOUPROU (exact)
UPDATE pointvente SET cod_agencia_saf = '004' WHERE cod_agencia_saf IS NULL AND libele = 'Dubreka'; -- SAF: DUBREKA (exact)
UPDATE pointvente SET cod_agencia_saf = '007' WHERE cod_agencia_saf IS NULL AND libele = 'Enta'; -- SAF: ENTA (exact)
UPDATE pointvente SET cod_agencia_saf = '115' WHERE cod_agencia_saf IS NULL AND libele = 'Faranah'; -- SAF: FARANAH (exact)
UPDATE pointvente SET cod_agencia_saf = '182' WHERE cod_agencia_saf IS NULL AND libele = 'Fassankony'; -- SAF: FASSANKONY (exact)
UPDATE pointvente SET cod_agencia_saf = '146' WHERE cod_agencia_saf IS NULL AND libele = 'Fouala'; -- SAF: FOUALAH (inclusion)
UPDATE pointvente SET cod_agencia_saf = '113' WHERE cod_agencia_saf IS NULL AND libele = 'Franwalia	'; -- SAF: FRANWALIAH (inclusion)
UPDATE pointvente SET cod_agencia_saf = '037' WHERE cod_agencia_saf IS NULL AND libele = 'Fria'; -- SAF: FRIA (exact)
UPDATE pointvente SET cod_agencia_saf = '155' WHERE cod_agencia_saf IS NULL AND libele = 'Gamaberema'; -- SAF: GAMABEREMA (exact)
UPDATE pointvente SET cod_agencia_saf = '061' WHERE cod_agencia_saf IS NULL AND libele = 'Gaoual'; -- SAF: GAOUAL (exact)
UPDATE pointvente SET cod_agencia_saf = '148' WHERE cod_agencia_saf IS NULL AND libele = 'Gbackedou'; -- SAF: GBACKEDOU (exact)
UPDATE pointvente SET cod_agencia_saf = '147' WHERE cod_agencia_saf IS NULL AND libele = 'Gbessoba'; -- SAF: GBESSOBA (exact)
UPDATE pointvente SET cod_agencia_saf = '076' WHERE cod_agencia_saf IS NULL AND libele = 'Gongoré'; -- SAF: GONGORE (exact)
UPDATE pointvente SET cod_agencia_saf = '162' WHERE cod_agencia_saf IS NULL AND libele = 'Gouecke'; -- SAF: Gouécké (exact)
UPDATE pointvente SET cod_agencia_saf = '168' WHERE cod_agencia_saf IS NULL AND libele = 'Gueckedou'; -- SAF: GUECKEDOU (exact)
UPDATE pointvente SET cod_agencia_saf = '099' WHERE cod_agencia_saf IS NULL AND libele = 'Kaboukaria'; -- SAF: Kaboukaria (exact)
UPDATE pointvente SET cod_agencia_saf = '062' WHERE cod_agencia_saf IS NULL AND libele = 'Kakoni'; -- SAF: KAKONI (exact)
UPDATE pointvente SET cod_agencia_saf = '141' WHERE cod_agencia_saf IS NULL AND libele = 'Kalinko'; -- SAF: KALINKO (exact)
UPDATE pointvente SET cod_agencia_saf = '005' WHERE cod_agencia_saf IS NULL AND libele = 'Kaloum'; -- SAF: KALOUM (exact)
UPDATE pointvente SET cod_agencia_saf = '033' WHERE cod_agencia_saf IS NULL AND libele = 'Kamsar'; -- SAF: KAMSAR (exact)
UPDATE pointvente SET cod_agencia_saf = '060' WHERE cod_agencia_saf IS NULL AND libele = 'Kankalabé'; -- SAF: KANAKALABE (verifie manuellement)
UPDATE pointvente SET cod_agencia_saf = '077' WHERE cod_agencia_saf IS NULL AND libele = 'Kankan'; -- SAF: KANKAN (exact)
UPDATE pointvente SET cod_agencia_saf = '086' WHERE cod_agencia_saf IS NULL AND libele = 'Kantoumanina'; -- SAF: KANTOUMANINA (exact)
UPDATE pointvente SET cod_agencia_saf = '130' WHERE cod_agencia_saf IS NULL AND libele = 'Kassadou'; -- SAF: KASSADOU (exact)
UPDATE pointvente SET cod_agencia_saf = '101' WHERE cod_agencia_saf IS NULL AND libele = 'Kerouané'; -- SAF: KEROUANE (exact)
UPDATE pointvente SET cod_agencia_saf = '017' WHERE cod_agencia_saf IS NULL AND libele = 'Kindia'; -- SAF: KINDIA (exact)
UPDATE pointvente SET cod_agencia_saf = '114' WHERE cod_agencia_saf IS NULL AND libele = 'Kintinia'; -- SAF: KINTINIAN (inclusion)
UPDATE pointvente SET cod_agencia_saf = '123' WHERE cod_agencia_saf IS NULL AND libele = 'Kissidougou'; -- SAF: KISSIDOUGOU (exact)
UPDATE pointvente SET cod_agencia_saf = '166' WHERE cod_agencia_saf IS NULL AND libele = 'Kobela'; -- SAF: Kobéla (exact)
UPDATE pointvente SET cod_agencia_saf = '120' WHERE cod_agencia_saf IS NULL AND libele = 'Kobikoro'; -- SAF: KOBIKORO (exact)
UPDATE pointvente SET cod_agencia_saf = '059' WHERE cod_agencia_saf IS NULL AND libele = 'Koin'; -- SAF: KOIN (exact)
UPDATE pointvente SET cod_agencia_saf = '158' WHERE cod_agencia_saf IS NULL AND libele = 'Kokota'; -- SAF: KOKOTA (exact)
UPDATE pointvente SET cod_agencia_saf = '032' WHERE cod_agencia_saf IS NULL AND libele = 'Kolaboui'; -- SAF: KOLABOUI (exact)
UPDATE pointvente SET cod_agencia_saf = '027' WHERE cod_agencia_saf IS NULL AND libele = 'Kolia'; -- SAF: KOLIA (exact)
UPDATE pointvente SET cod_agencia_saf = '100' WHERE cod_agencia_saf IS NULL AND libele = 'Komola'; -- SAF: Komola (exact)
UPDATE pointvente SET cod_agencia_saf = '058' WHERE cod_agencia_saf IS NULL AND libele = 'Konah'; -- SAF: KONAH (exact)
UPDATE pointvente SET cod_agencia_saf = '126' WHERE cod_agencia_saf IS NULL AND libele = 'Kondiadou'; -- SAF: KONDIADOU (exact)
UPDATE pointvente SET cod_agencia_saf = '092' WHERE cod_agencia_saf IS NULL AND libele = 'Kondianakoro'; -- SAF: KONDIANAKORO (exact)
UPDATE pointvente SET cod_agencia_saf = '180' WHERE cod_agencia_saf IS NULL AND libele = 'Kouankan'; -- SAF: KOUANKAN (exact)
UPDATE pointvente SET cod_agencia_saf = '057' WHERE cod_agencia_saf IS NULL AND libele = 'Koubia'; -- SAF: KOUBIA (exact)
UPDATE pointvente SET cod_agencia_saf = '028' WHERE cod_agencia_saf IS NULL AND libele = 'Koukoudé'; -- SAF: KOUKOUDE (exact)
UPDATE pointvente SET cod_agencia_saf = '163' WHERE cod_agencia_saf IS NULL AND libele = 'Koulé'; -- SAF: Koulé (exact)
UPDATE pointvente SET cod_agencia_saf = '095' WHERE cod_agencia_saf IS NULL AND libele = 'Koumana'; -- SAF: Koumana (exact)
UPDATE pointvente SET cod_agencia_saf = '063' WHERE cod_agencia_saf IS NULL AND libele = 'Koumbia'; -- SAF: KOUMBIA (exact)
UPDATE pointvente SET cod_agencia_saf = '065' WHERE cod_agencia_saf IS NULL AND libele = 'Koundara'; -- SAF: KOUNDARA (exact)
UPDATE pointvente SET cod_agencia_saf = '091' WHERE cod_agencia_saf IS NULL AND libele = 'Koundian'; -- SAF: KOUNDIAN (exact)
UPDATE pointvente SET cod_agencia_saf = '170' WHERE cod_agencia_saf IS NULL AND libele = 'Koundou'; -- SAF: KOUNDOU (exact)
UPDATE pointvente SET cod_agencia_saf = '045' WHERE cod_agencia_saf IS NULL AND libele = 'Kouramangui'; -- SAF: KOURAMANGUI (exact)
UPDATE pointvente SET cod_agencia_saf = '107' WHERE cod_agencia_saf IS NULL AND libele = 'Kouremale'; -- SAF: KOUREMALE (exact)
UPDATE pointvente SET cod_agencia_saf = '094' WHERE cod_agencia_saf IS NULL AND libele = 'Kouroussa'; -- SAF: Kouroussa (exact)
UPDATE pointvente SET cod_agencia_saf = '181' WHERE cod_agencia_saf IS NULL AND libele = 'Koyamah'; -- SAF: KOYAMAH (exact)
UPDATE pointvente SET cod_agencia_saf = '043' WHERE cod_agencia_saf IS NULL AND libele = 'Labé'; -- SAF: LABE (exact)
UPDATE pointvente SET cod_agencia_saf = '156' WHERE cod_agencia_saf IS NULL AND libele = 'Lainé'; -- SAF: LAINE (exact)
UPDATE pointvente SET cod_agencia_saf = '046' WHERE cod_agencia_saf IS NULL AND libele = 'Lelouma'; -- SAF: LELOUMA (exact)
UPDATE pointvente SET cod_agencia_saf = '070' WHERE cod_agencia_saf IS NULL AND libele = 'Linsan'; -- SAF: linsan (exact)
UPDATE pointvente SET cod_agencia_saf = '093' WHERE cod_agencia_saf IS NULL AND libele = 'Loila'; -- SAF: LOILA (exact)
UPDATE pointvente SET cod_agencia_saf = '154' WHERE cod_agencia_saf IS NULL AND libele = 'Lola'; -- SAF: LOLA (exact)
UPDATE pointvente SET cod_agencia_saf = '174' WHERE cod_agencia_saf IS NULL AND libele = 'Macenta'; -- SAF: MACENTA (exact)
UPDATE pointvente SET cod_agencia_saf = '009' WHERE cod_agencia_saf IS NULL AND libele = 'Madina'; -- SAF: MADINA (exact)
UPDATE pointvente SET cod_agencia_saf = '021' WHERE cod_agencia_saf IS NULL AND libele = 'Madina Oula'; -- SAF: MADINA OULA (exact)
UPDATE pointvente SET cod_agencia_saf = '003' WHERE cod_agencia_saf IS NULL AND libele = 'Maferinyah'; -- SAF: MAFERINYAH (exact)
UPDATE pointvente SET cod_agencia_saf = '111' WHERE cod_agencia_saf IS NULL AND libele = 'Maleah'; -- SAF: MALEAH (exact)
UPDATE pointvente SET cod_agencia_saf = '048' WHERE cod_agencia_saf IS NULL AND libele = 'Mali'; -- SAF: MALI (exact)
UPDATE pointvente SET cod_agencia_saf = '019' WHERE cod_agencia_saf IS NULL AND libele = 'Mambia'; -- SAF: MAMBIA (exact)
UPDATE pointvente SET cod_agencia_saf = '069' WHERE cod_agencia_saf IS NULL AND libele = 'Mamou'; -- SAF: mamou (exact)
UPDATE pointvente SET cod_agencia_saf = '082' WHERE cod_agencia_saf IS NULL AND libele = 'Mandiana'; -- SAF: MANDIANA (exact)
UPDATE pointvente SET cod_agencia_saf = '034' WHERE cod_agencia_saf IS NULL AND libele = 'Mankountan'; -- SAF: MANKOUNTAN (exact)
UPDATE pointvente SET cod_agencia_saf = '006' WHERE cod_agencia_saf IS NULL AND libele = 'Matoto'; -- SAF: MATOTO (exact)
UPDATE pointvente SET cod_agencia_saf = '139' WHERE cod_agencia_saf IS NULL AND libele = 'Mbonet'; -- agence SAF combinee 139 'DINGUIRAYE ET MBONET' (partagee avec le PS Dinguiraye) -- SAF: DINGUIRAYE ET MBONET (inclusion)
UPDATE pointvente SET cod_agencia_saf = '079' WHERE cod_agencia_saf IS NULL AND libele = 'Missamana'; -- SAF: MISSAMANA (exact)
UPDATE pointvente SET cod_agencia_saf = '022' WHERE cod_agencia_saf IS NULL AND libele = 'Missira'; -- SAF: MISSIRA (exact)
UPDATE pointvente SET cod_agencia_saf = '143' WHERE cod_agencia_saf IS NULL AND libele = 'Moribadou'; -- SAF: MORIBADOU (exact)
UPDATE pointvente SET cod_agencia_saf = '078' WHERE cod_agencia_saf IS NULL AND libele = 'Moribayah'; -- SAF: MORIBAYA (inclusion)
UPDATE pointvente SET cod_agencia_saf = '085' WHERE cod_agencia_saf IS NULL AND libele = 'Morodou'; -- SAF: MORODOU (exact)
UPDATE pointvente SET cod_agencia_saf = '015' WHERE cod_agencia_saf IS NULL AND libele = 'Moussayah'; -- SAF: MOUSSAYAH (exact)
UPDATE pointvente SET cod_agencia_saf = '160' WHERE cod_agencia_saf IS NULL AND libele = 'N''Zerekoré 1'; -- SAF: N'Zérékoré 1 (exact)
UPDATE pointvente SET cod_agencia_saf = '161' WHERE cod_agencia_saf IS NULL AND libele = 'N''Zerekoré 2'; -- SAF: N'Zérékoré 2 (exact)
UPDATE pointvente SET cod_agencia_saf = '108' WHERE cod_agencia_saf IS NULL AND libele = 'Niandankoro'; -- SAF: NIANDANKÖRÖ (exact)
UPDATE pointvente SET cod_agencia_saf = '087' WHERE cod_agencia_saf IS NULL AND libele = 'Niantanina	'; -- SAF: NIANTANINA (exact)
UPDATE pointvente SET cod_agencia_saf = '084' WHERE cod_agencia_saf IS NULL AND libele = 'Ourola'; -- SAF: OUROLA (exact)
UPDATE pointvente SET cod_agencia_saf = '167' WHERE cod_agencia_saf IS NULL AND libele = 'Palé'; -- SAF: Palé (exact)
UPDATE pointvente SET cod_agencia_saf = '178' WHERE cod_agencia_saf IS NULL AND libele = 'Panziazou'; -- SAF: PANZIAZOU (exact)
UPDATE pointvente SET cod_agencia_saf = '150' WHERE cod_agencia_saf IS NULL AND libele = 'Pela'; -- SAF: PELA (exact)
UPDATE pointvente SET cod_agencia_saf = '052' WHERE cod_agencia_saf IS NULL AND libele = 'Pita'; -- SAF: PITA (exact)
UPDATE pointvente SET cod_agencia_saf = '050' WHERE cod_agencia_saf IS NULL AND libele = 'Popodara'; -- SAF: POPODARA (exact)
UPDATE pointvente SET cod_agencia_saf = '075' WHERE cod_agencia_saf IS NULL AND libele = 'Poredaka'; -- SAF: POREDAKA (exact)
UPDATE pointvente SET cod_agencia_saf = '164' WHERE cod_agencia_saf IS NULL AND libele = 'Samoe'; -- SAF: Samoé (exact)
UPDATE pointvente SET cod_agencia_saf = '117' WHERE cod_agencia_saf IS NULL AND libele = 'Sandenia'; -- SAF: SANDENIA (exact)
UPDATE pointvente SET cod_agencia_saf = '124' WHERE cod_agencia_saf IS NULL AND libele = 'Sangardo'; -- SAF: SANGARDO (exact)
UPDATE pointvente SET cod_agencia_saf = '024' WHERE cod_agencia_saf IS NULL AND libele = 'Sangaredi'; -- SAF: SANGAREDI (exact)
UPDATE pointvente SET cod_agencia_saf = '098' WHERE cod_agencia_saf IS NULL AND libele = 'Saraya'; -- SAF: Saraya (exact)
UPDATE pointvente SET cod_agencia_saf = '066' WHERE cod_agencia_saf IS NULL AND libele = 'Sareboido'; -- SAF: SAREBOIDO (exact)
UPDATE pointvente SET cod_agencia_saf = '179' WHERE cod_agencia_saf IS NULL AND libele = 'Seredou'; -- SAF: SEREDOU (exact)
UPDATE pointvente SET cod_agencia_saf = '105' WHERE cod_agencia_saf IS NULL AND libele = 'Siguiri'; -- SAF: SIGUIRI (exact)
UPDATE pointvente SET cod_agencia_saf = '112' WHERE cod_agencia_saf IS NULL AND libele = 'Siguirini'; -- SAF: SIGUIRINI (exact)
UPDATE pointvente SET cod_agencia_saf = '016' WHERE cod_agencia_saf IS NULL AND libele = 'Sikhourou'; -- SAF: SIKHOUROU (exact)
UPDATE pointvente SET cod_agencia_saf = '145' WHERE cod_agencia_saf IS NULL AND libele = 'Sinko'; -- SAF: SINKO (exact)
UPDATE pointvente SET cod_agencia_saf = '041' WHERE cod_agencia_saf IS NULL AND libele = 'Sinta'; -- SAF: SINTA (exact)
UPDATE pointvente SET cod_agencia_saf = '010' WHERE cod_agencia_saf IS NULL AND libele = 'Sonfonia'; -- SAF: SONFONIA (exact)
UPDATE pointvente SET cod_agencia_saf = '122' WHERE cod_agencia_saf IS NULL AND libele = 'Songoyah'; -- SAF: SONGOYAH (exact)
UPDATE pointvente SET cod_agencia_saf = '165' WHERE cod_agencia_saf IS NULL AND libele = 'Soulouta'; -- SAF: Soulouta (exact)
UPDATE pointvente SET cod_agencia_saf = '008' WHERE cod_agencia_saf IS NULL AND libele = 'Taouyah'; -- SAF: TAOUYAH (exact)
UPDATE pointvente SET cod_agencia_saf = '039' WHERE cod_agencia_saf IS NULL AND libele = 'Tarihoye'; -- SAF: TARIHOYE (exact)
UPDATE pointvente SET cod_agencia_saf = '038' WHERE cod_agencia_saf IS NULL AND libele = 'Telimelé'; -- SAF: TELIMELE (exact)
UPDATE pointvente SET cod_agencia_saf = '172' WHERE cod_agencia_saf IS NULL AND libele = 'Temessadou'; -- SAF: TEMESSADOU (exact)
UPDATE pointvente SET cod_agencia_saf = '067' WHERE cod_agencia_saf IS NULL AND libele = 'Termessé'; -- SAF: TERMESSE (exact)
UPDATE pointvente SET cod_agencia_saf = '055' WHERE cod_agencia_saf IS NULL AND libele = 'Timbi Madina'; -- SAF: TIMBI-MADINA (exact)
UPDATE pointvente SET cod_agencia_saf = '081' WHERE cod_agencia_saf IS NULL AND libele = 'Tintioulen'; -- SAF: TINTIOULEN (exact)
UPDATE pointvente SET cod_agencia_saf = '118' WHERE cod_agencia_saf IS NULL AND libele = 'Tiro'; -- SAF: TIRO (exact)
UPDATE pointvente SET cod_agencia_saf = '133' WHERE cod_agencia_saf IS NULL AND libele = 'Tokounou'; -- SAF: TOKOUNOU (exact)
UPDATE pointvente SET cod_agencia_saf = '064' WHERE cod_agencia_saf IS NULL AND libele = 'Touba'; -- SAF: TOUBA (exact)
UPDATE pointvente SET cod_agencia_saf = '029' WHERE cod_agencia_saf IS NULL AND libele = 'Tougnifily'; -- SAF: TOUGNIFILY (exact)
UPDATE pointvente SET cod_agencia_saf = '056' WHERE cod_agencia_saf IS NULL AND libele = 'Tougué'; -- SAF: TOUGUE (exact)
UPDATE pointvente SET cod_agencia_saf = '157' WHERE cod_agencia_saf IS NULL AND libele = 'Tounkarata'; -- SAF: TOUNKARATA (exact)
UPDATE pointvente SET cod_agencia_saf = '131' WHERE cod_agencia_saf IS NULL AND libele = 'Yende Milimou'; -- SAF: YENDE (inclusion)
UPDATE pointvente SET cod_agencia_saf = '132' WHERE cod_agencia_saf IS NULL AND libele = 'Yombiro'; -- SAF: YOMBIRO (exact)
UPDATE pointvente SET cod_agencia_saf = '149' WHERE cod_agencia_saf IS NULL AND libele = 'Yomou'; -- SAF: YOMOU (exact)
UPDATE pointvente SET cod_agencia_saf = '036' WHERE cod_agencia_saf IS NULL AND libele = 'koba'; -- SAF: KOBA (exact)
UPDATE pointvente SET cod_agencia_saf = '035' WHERE cod_agencia_saf IS NULL AND libele = 'tanene'; -- SAF: TANENE (exact)

-- Correspondances verifiees manuellement (variantes d'orthographe evidentes)
UPDATE pointvente SET cod_agencia_saf = '134' WHERE cod_agencia_saf IS NULL AND libele = 'Arfamoussayah'; -- SAF: ARFAMOUSSAYA
UPDATE pointvente SET cod_agencia_saf = '072' WHERE cod_agencia_saf IS NULL AND libele = 'Saramoussayah'; -- SAF: saramoussaya

-- Controle des PS restes sans correspondance :
-- SELECT id, libele FROM pointvente WHERE cod_agencia_saf IS NULL ORDER BY libele;
