-- V137 : personnels badgés au siège (référence : liste DRH « personnebadge »).
-- Le rapprochement des présences ne contrôle QUE ces agents : les autres membres
-- du personnel (réseau, sans badge) ne sortent plus en « absent non justifié ».
ALTER TABLE info_personnel ADD COLUMN IF NOT EXISTS badge_siege BOOLEAN NOT NULL DEFAULT FALSE;

-- Les matricules déjà présents sont marqués badgés (nom/prénom conservés),
-- les manquants sont créés depuis la liste de la badgeuse.
INSERT INTO info_personnel (matricule, nom, prenom, badge_siege) VALUES
    ('13', 'BAH', 'Abdoulaye Simbé', TRUE),
    ('38', 'DELAMOU', 'Siba', TRUE),
    ('42', 'BARRY', 'Boubacar', TRUE),
    ('57', 'CISSE', 'Sokhona', TRUE),
    ('60', 'BAH', 'Ibrahima Labé', TRUE),
    ('62', 'MAGASSOUBA', 'Ibrahima Kalil', TRUE),
    ('72', 'DELAMOU', 'Paul', TRUE),
    ('75', 'BOCOUM', 'Souleymane', TRUE),
    ('76', 'DIALLO', 'Ibrahima', TRUE),
    ('82', 'BAH', 'Ibrahima Pita', TRUE),
    ('93', 'DIALLO', 'Habib', TRUE),
    ('95', 'BAH', 'Hassane', TRUE),
    ('102', 'SAMPIL', 'Sekou souleymane', TRUE),
    ('106', 'BARRY', 'Mody Sory', TRUE),
    ('109', 'TOURE', 'Abdoulaye', TRUE),
    ('113', 'CONDE', 'Sékou Mohamed', TRUE),
    ('119', 'CAMARA', 'Seny', TRUE),
    ('133', 'SAOULOMOU', 'Thoron', TRUE),
    ('138', 'CAMARA', 'Youssouf Décazi', TRUE),
    ('139', 'TOURE', 'Abdoulaye Sadio', TRUE),
    ('147', 'SYLLA', 'Aïcha', TRUE),
    ('148', 'CAMARA', 'Fantamady', TRUE),
    ('149', 'TCHIDIMBO', 'Marie Paulette', TRUE),
    ('162', 'KEITA', 'Sidiki', TRUE),
    ('166', 'DIALLO', 'Alpha Ibrahima 3', TRUE),
    ('170', 'BAH', 'Mamadou Baïlo', TRUE),
    ('172', 'BALDE', 'Mamadou Aliou', TRUE),
    ('187', 'GOMOU', 'David Foromo', TRUE),
    ('194', 'LOUA', 'Samuel Tokpa', TRUE),
    ('198', 'SOUMAORO', 'Aboubacar', TRUE),
    ('203', 'DOUMBOUYA', 'Moussa', TRUE),
    ('214', 'CHERIF', 'Aboubacar Sidiki', TRUE),
    ('215', 'CISSE', 'M''mah', TRUE),
    ('224', 'CONDE', 'Daouda', TRUE),
    ('225', 'SOUMAORO', 'Massa', TRUE),
    ('244', 'BARRY', 'Mamadou Safayiou', TRUE),
    ('272', 'KOULIBALY', 'Ibrahima Sory', TRUE),
    ('278', 'BALDE', 'Ibrahima Oumou', TRUE),
    ('280', 'CAMARA', 'Fanta', TRUE),
    ('283', 'DIALLO', 'Mariama Lamarana', TRUE),
    ('301', 'BIMOU', 'Antoine', TRUE),
    ('306', 'HABA', 'Moriba 3', TRUE),
    ('308', 'LOUA', 'Alphonse', TRUE),
    ('332', 'KOUROUMA', 'Tokpa Souana', TRUE),
    ('347', 'SALL', 'Mamadou Bobo', TRUE),
    ('349', 'DIALLO', 'Fatoumata Binta', TRUE),
    ('351', 'DIALLO', 'Alpha Oumarou Lalbab', TRUE),
    ('353', 'SIDIBE', 'Sékou', TRUE),
    ('363', 'TRAORE', 'Boh Lancei', TRUE),
    ('379', 'KOLIE', 'Foromo', TRUE),
    ('388', 'BAH', 'Mamadou Lamarana', TRUE),
    ('394', 'SANGARE', 'KADIATOU', TRUE),
    ('410', 'DOUMBOUYA', 'SEKOU', TRUE),
    ('420', 'FOFANA', 'MMAHAWA', TRUE),
    ('424', 'CAMARA', 'ABOUBACAR DEMBA', TRUE),
    ('442', 'DIALLO', 'SALIMATOU MOUCTAR', TRUE),
    ('450', 'SOW', 'THIERNO MAMADOU BAÏLO', TRUE),
    ('452', 'GROVOGUI', 'KEKOURA', TRUE),
    ('474', 'KOUROUMA', 'ODIA', TRUE),
    ('483', 'MARA', 'Kanféla', TRUE),
    ('485', 'TRAORE', 'Sidiki', TRUE),
    ('487', 'CAMARA', 'Sekou', TRUE),
    ('488', 'SIDIBE', 'Amadou Sadjo', TRUE),
    ('489', 'DOUKOURE', 'Salifou', TRUE),
    ('493', 'DORE', 'Appoline', TRUE),
    ('494', 'CAMARA', 'Fanta', TRUE),
    ('629', 'BENBO', 'Assemien Daniel', TRUE),
    ('630', 'DIALLO', 'Moustapha', TRUE),
    ('632', 'THIAM', 'Tidiane', TRUE),
    ('633', 'SAMB', 'Aîssatou Mandela', TRUE),
    ('634', 'SYLLA', 'Ousmane', TRUE)
ON CONFLICT (matricule) DO UPDATE SET badge_siege = TRUE, updated_at = NOW();
