import { CreditoPKId } from './credit.pkid';

export interface Credit {
    creditoPKId: CreditoPKId;
    codCliente: string;
    codUsuarios: string;
    monCredito: number;
    indEstado: string;
    idCuenta: string;
    per_INT: string | null;
    tip_MANEJO: string | null;
    cod_REFERENTE: string;
    ind_COB_CARGOS: string;
    ind_BLOQUEO: string;
    num_CICLO: number;
    tip_LINEA: string | null;
    cant_HECTAREAS: number | null;
    fec_CANCELACION: string | null;
    fec_ING_COBRO: string;
    per_COMISION: string;
    tip_DESEMBOLSO: string;
    tip_REG_COBRO: number;
    tasa_EFECTIVA: number;
    fec_PROVISION: string;
    gracia_MORA: number;
    id_EXTERNO: string | null;
    fec_SAL_COBRO: string;
    fec_INICIO_PLAN: string | null;
    fec_RENOVACION: string | null;
    mon_INT_CUOTA: number;
    ind_SOBREGIRO: string;
    per_MORA: string;
    tip_INTERES: string;
    per_CUOTA: string;
    cod_OFICIAL: string | null;
    num_LINEA: string | null;
    cod_GRUPO_SOL: string | null;
    ind_CALC_MORA: string;
    ind_COB_POLIZA: string;
    tip_TASA: string;
    ind_LINEA: string;
    tip_MORA: string;
    ind_COB_CUOTA: string;
    por_SOBREGIRO: number;
    plazo_ADICIONAL: number;
    per_REV_TASA: string;
    cod_ZONA: string | null;
    mon_SALDO: number;
    mon_PROVISION: number | null;
    tip_REVISION: string;
    cod_DIRECCION: string;
    cod_ASOCIACION: string | null;
    fec_ADICION: string | null;
    cod_MONEDA: string;
    ind_FORMA_PAGO: string;
    fec_PRORROGA: string | null;
    fec_RECONOC_INT: string | null;
    tip_COMISION: string;
    mon_PRINCIPAL_CUOTA: number;
    mon_DESEMBOLSADO: number;
    ind_COBRA_INT_INICIAL: string | null;
    mon_INT_ANTES_CJ: number;
    fec_ULT_PAGO_INTERESES: string;
    fec_PROX_COMISION: string | null;
    fec_ULT_REVISION: string | null;
    mon_SUSPEN_INTERESES: number | null;
    mon_PAGADO_INTERESES: number;
    fec_ULT_DESEMBOLSO: string;
    tip_MODALIDAD_COBRO_ESP: string;
    fec_PROX_REVISION: string | null;
    mon_PAGADO_PRINCIPAL: number;
    mon_INT_ANTICIPADOS: number;
    ind_CALIF_MANUAL: string;
    cod_ESTADO_CONTABLE: string | null;
    ind_EXCLUSION_PAGO: string;
    val_VARIACION_MORA: number;
    mon_INT_MORA_ACUMULA: number;
    cod_USUARIO_PROVISION: string | null;
    cod_CALIFICACION: string;
    ind_CAPITALIZA_INT: string | null;
    tasa_INT_VAL_AGREGADO: number | null;
    mon_REVALORIZACION: number;
    gracia_PRINCIPAL: number;
    mon_INT_SUSPENSO: number;
    mon_INT_ACUMULADO: number;
    fec_ULT_PAGO_PRINCIPAL: string;
    val_VARIACION_BASE: number;
    mon_INT_MORA_SUSPENSO: number;
    fec_PRIMER_DESEMBOLSO: string;
    fec_ULT_PAGO_COMISION: string | null;
    periodo_CAPITALIZACION: string | null;
    fec_INI_PAGO_PRINC: string;
    fec_CALIFICACION: string;
    mon_SUSPEN_PRINCIPAL: number | null;
    fec_ULT_PAGO_MORA: string;
    ind_COB_COMISION: string;
    ind_CONTINUA_COBRO_INT: string;
    mon_COMISION_NORMAL: number;
    fec_APERTURA: string;
    cod_ACTIVIDAD: string;
    tip_MODALIDAD_COBRO: string;
    cod_PLAN_INVERSION: string;
    fec_ULT_REVISION_MORA: string | null;
    cod_SUBSUBACTIVIDAD: string;
    ind_TASA_VAL_AGREGADO: string | null;
    tip_CREDITO: number;
    cod_ORIGEN: string;
    cod_TASA_INT: string;
    tip_CUOTA: string;
    observaciones: string;
    cod_TASA_MORA: string;
    cod_EJECUTIVO: string;
    dia_PAGO: string;
    cod_SUBACTIV: string;
    mon_CUOTA: number;
    tasa_INTERES: number;
    tasa_MORA: number;
    tip_CALENDARIO: number;
    fec_VENCIMIENTO: string;
    cod_FINANCIADOR: string | null;
    cod_PLAZO: number;
    cant_CUOTAS: number;
    num_DESTINO: string;
    plazo_CREDITO: number;
}
