name: CI - Build & Test Microservices

on:
  pull_request:
    branches: [main]
    paths:
      - micro-digiservices/**
  push:
    branches: [develop]
    paths:
      - micro-digiservices/**

jobs:
  test-microservices:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ci_test_user
          POSTGRES_PASSWORD: ci_test_password
          POSTGRES_DB: ci_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Exemple : compile et tests unitaires sur chaque microservice
      - name: Compile & Unit Test - Userservice
        run: |
          cd micro-digiservices/userservice
          mvn clean verify

      - name: Compile & Unit Test - AuthorizationServer
        run: |
          cd micro-digiservices/authorizationserver
          mvn clean verify

      - name: Compile & Unit Test - Ecreditservice
        run: |
          cd micro-digiservices/ecreditservice
          mvn clean verify

      # ... Répète pour chaque microservice

      # Exemple migration Flyway sur BDD de test
      - name: Flyway Migration Test
        run: |
          cd micro-digiservices/database-migrations
          mvn flyway:migrate -Dflyway.url=jdbc:postgresql://localhost:5432/ci_test_db \
              -Dflyway.user=ci_test_user \
              -Dflyway.password=ci_test_password

      # (Ajoute des jobs SonarCloud, Checkstyle, etc si besoin)

      - name: Success badge
        run: echo "✅ Build & Tests passed !"
